version: '3'
services:

  backend:
    build:
      context: ./backend
    ports:
      - "8888:8888"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
